language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ti3rn1210/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Ti3rn1210/docker-react npm run test